export const THERAPY_CATALOG = [
  { name: 'Red Light Therapy', description: 'Red and near-infrared light for mitochondrial function, recovery, skin health, collagen production, wound healing, muscle recovery, inflammation reduction, sleep regulation, and pain management.', duration_min: 30, pricing_tier: 'membership' as const, booking_type: 'slot' as const, icon: '💡' },
  { name: 'Cryotherapy', description: 'Whole-body or localized cold exposure (CRYONiQ) for inflammation reduction, muscle soreness, pain relief, recovery, circulation, alertness, and mood enhancement.', duration_min: 15, pricing_tier: 'membership' as const, booking_type: 'slot' as const, icon: '❄️' },
  { name: 'Neuro Relaxation', description: 'Neuroacoustic therapy, guided meditation, vagus nerve stimulation, brainwave entrainment for stress management, ANS balance, burnout reduction, and sleep optimization.', duration_min: 45, pricing_tier: 'membership' as const, booking_type: 'slot' as const, icon: '🧠' },
  { name: 'Aromatherapy & Sound Healing', description: 'Essential oils plus sound frequencies, binaural beats, vibrational therapy for relaxation, mood enhancement, anxiety reduction, and meditation support.', duration_min: 45, pricing_tier: 'membership' as const, booking_type: 'slot' as const, icon: '🎵' },
  { name: 'Breathwork & Yoga', description: 'Breathwork, lung training, respiratory muscle strengthening, CO2 tolerance, VO2 improvement, stress reduction, and athletic endurance.', duration_min: 60, pricing_tier: 'membership' as const, booking_type: 'class' as const, icon: '🧘' },
  { name: 'IV Nutrition / Longevity Drip', description: 'IV delivery of vitamins, minerals, amino acids, antioxidants, NAD+, glutathione for hydration, fatigue recovery, nutrient replenishment, and wellness optimization.', duration_min: 60, pricing_tier: 'addon' as const, booking_type: 'slot' as const, icon: '💉' },
  { name: 'Hyperbaric Oxygen Chamber', description: 'Oxygen under increased pressure for wound healing, recovery, cognitive support, tissue repair, and performance recovery.', duration_min: 60, pricing_tier: 'addon' as const, booking_type: 'slot' as const, icon: '🫧' },
  { name: 'Ice Bath / Cold Plunge / Steam', description: 'Contrast thermotherapy for circulation, muscle recovery, stress adaptation, cardiovascular conditioning, and ANS conditioning.', duration_min: 30, pricing_tier: 'membership' as const, booking_type: 'slot' as const, icon: '🧊' },
  { name: 'Physiotherapy', description: 'Mobility, muscle preservation, joint function, posture, pain-free aging, movement quality, and strength maintenance.', duration_min: 60, pricing_tier: 'addon' as const, booking_type: 'slot' as const, icon: '🦴' },
  { name: 'Diet Therapy Consultation', description: 'Nutrition programs via Lami.fit: weight loss, fat loss, muscle preservation, PCOS, diabetes reversal, gut health, anti-inflammatory, menopause support, sports nutrition, and healthy aging.', duration_min: 60, pricing_tier: 'addon' as const, booking_type: 'consultation' as const, icon: '🥗' },
  { name: 'Cognitive Therapy', description: 'Cognitive rehabilitation and brain training via COGBAT: memory, attention, focus, executive function, processing speed, and problem-solving.', duration_min: 60, pricing_tier: 'addon' as const, booking_type: 'slot' as const, icon: '🧩' },
] as const;
